# Generated by Django 4.2.3 on 2023-08-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_book_authors_alter_comment_book_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
