# Generated by Django 4.2.3 on 2023-08-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_book_count_likes_comment_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'кніга', 'verbose_name_plural': 'кнігі'},
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='назва кнігі'),
        ),
    ]
